version: 2
 
sources:
  - name: prod
    schema: prod
    database: pr_db
    tables:
      - name: departments
        identifier: departments
      - name: employees
        identifier: employees